[package]
name = "alien-metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
serde_json = { version = "1" }
once_cell = { version = "1" }
thiserror = { version = "1.0" }
url = { version = "2.3.1" }
