{
 "title": "Alien Router Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Transfer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Rate",
   "type": "timeseries",
   "description": "Download Rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (increase(device_rx_bytes{instance=~\"$instance\", job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Upload Rate",
   "type": "timeseries",
   "description": "Upload Rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (increase(device_tx_bytes{instance=~\"$instance\", job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Downloaded Total",
   "type": "timeseries",
   "description": "Downloaded Total",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "device_rx_bytes{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uploaded Total",
   "type": "timeseries",
   "description": "Uploaded Total",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "device_tx_bytes{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Happiness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Happiness",
   "type": "timeseries",
   "description": "Happiness",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "device_happiness{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "timeseries",
   "description": "Signal",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "device_signal{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Device RxBitrate",
   "type": "timeseries",
   "description": "Device RxBitrate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "device_rx_bitrate{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Device TxBitrate",
   "type": "timeseries",
   "description": "Device TxBitrate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "device_tx_bitrate{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Scraper Stuff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Alien Metrics Scraped",
   "type": "timeseries",
   "description": "Alien Metrics Scraped",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "round(sum(increase(scrape_requests_total{instance=~\"$instance\", job=~\"$job\"}[$__interval])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alien Metrics Scrape Errors",
   "type": "timeseries",
   "description": "Alien Metrics Scrape Errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "round(increase(scrape_requests_error_total{instance=~\"$instance\", job=~\"$job\"}[$__interval]), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Endpoint Scraped",
   "type": "timeseries",
   "description": "Prometheus Endpoint Scraped",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "round(increase(http_requests_total{instance=~\"$instance\", job=~\"$job\"}[$__interval]), 1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}