name: CI
on:
  push:
    paths:
    - '.github/workflows/ci.yml'
    - 'src/**'
    - 'mocks/**'
    - 'Cargo.lock'
    - 'Cargo.toml'
  pull_request:
    paths:
    - '.github/workflows/ci.yml'
    - 'src/**'
    - 'mocks/**'
    - 'Cargo.lock'
    - 'Cargo.toml'
  schedule:
    - cron: '0 0 * * 0'
jobs:
  checks:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # latest
        with:
          toolchain: ${{ matrix.rust }}
      - name: Rust cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          shared-key: common
      - name: Cargo check
        run: cargo check --workspace

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # latest
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Rust cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          shared-key: common
      - name: Install cargo-audit and cargo-machete
        run: cargo install --locked cargo-audit cargo-machete
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo doc
        run: cargo doc --workspace --no-deps
      - name: Cargo clippy
        run: cargo clippy --workspace --tests -- -D warnings
      - name: Cargo audit
        run: cargo audit
      - name: Cargo machete
        run: cargo machete

  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: [checks, lints]
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # latest
        with:
          toolchain: ${{ matrix.rust }}
      - name: Rust cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          shared-key: common
      - name: Cargo test
        run: cargo test --workspace
