name: CI

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/ci.yml'
    - 'src/**'
    - 'mocks/**'
    - 'Cargo.lock'
    - 'Cargo.toml'
  pull_request:
    paths:
    - '.github/workflows/ci.yml'
    - 'src/**'
    - 'mocks/**'
    - 'Cargo.lock'
    - 'Cargo.toml'
  schedule:
    - cron: '0 0 * * 0'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      CARGO_NET_RETRY: 10
      RUST_BACKTRACE: short
    steps:
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Cache Rust toolchain
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: rust-toolchain-${{ runner.os }}-stable-clippy-rustfmt
          restore-keys: |
            rust-toolchain-${{ runner.os }}-stable-
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # latest
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cache Rust dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache cargo tools
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.cargo/bin
          key: cargo-tools-${{ runner.os }}-audit-machete
          restore-keys: |
            cargo-tools-${{ runner.os }}-
      - name: Install cargo-audit and cargo-machete
        run: |
          set -e
          if ! command -v cargo-audit >/dev/null 2>&1; then
            echo "Installing cargo-audit..."
            cargo install --locked cargo-audit
          else
            echo "cargo-audit already installed: $(cargo-audit --version)"
          fi
          if ! command -v cargo-machete >/dev/null 2>&1; then
            echo "Installing cargo-machete..."
            cargo install --locked cargo-machete
          else
            echo "cargo-machete already installed: $(cargo-machete --version)"
          fi
      - name: Cargo audit
        run: cargo audit
      - name: Cargo machete
        run: cargo machete
      - name: Cargo check
        run: cargo check --workspace
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo doc
        run: cargo doc --workspace --no-deps
      - name: Cargo clippy
        run: cargo clippy --workspace --tests -- -D warnings
      - name: Cargo test
        run: cargo test --workspace
