name: Grafana
on:
  push:
    paths:
    - 'grafana.json'
  pull_request:
    paths:
    - 'grafana.json'
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Install Grafana dashboard linter
        run: go install github.com/grafana/dashboard-linter@latest
      - name: Run Grafana dashboard linter
        run: dashboard-linter lint --strict --verbose grafana.json