name: Grafana

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/grafana.yml'
    - 'grafana.json'
  pull_request:
    paths:
    - '.github/workflows/grafana.yml'
    - 'grafana.json'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Download go.mod securely
        run: |
          curl -fsSL -H "User-Agent: GitHub Actions" \
            "https://raw.githubusercontent.com/grafana/dashboard-linter/main/go.mod" \
            -o go.mod
          # Verify file is not empty and contains expected content
          grep -q "module github.com/grafana/dashboard-linter" go.mod
      - name: Download go.sum securely
        run: |
          curl -fsSL -H "User-Agent: GitHub Actions" \
            "https://raw.githubusercontent.com/grafana/dashboard-linter/main/go.sum" \
            -o go.sum
          # Verify file exists and is not empty
          [ -s go.sum ]
      - name: Setup Golang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.25.1'
          cache: true
      - name: Install Grafana dashboard linter
        run: go install github.com/grafana/dashboard-linter@latest
      - name: Run Grafana dashboard linter
        run: dashboard-linter lint --strict --verbose grafana.json
